# Generated by Django 3.2.8 on 2021-12-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.CharField(default='test@mail.ru', max_length=100),
        ),
        migrations.AddField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(blank=True, upload_to='doctors/%Y/%m/%d'),
        ),
    ]
